jenkinsci/saml-plugin

pom.xml, src/main/java/org/jenkinsci/plugins/saml/SamlAuthenticationToken.java, src/main/java/org/jenkinsci/plugins/saml/SamlCrumbExclusion.java, src/main/java/org/jenkinsci/plugins/saml/SamlEncryptionData.java, src/main/java/org/jenkinsci/plugins/saml/SamlGroupAuthority.java, src/main/java/org/jenkinsci/plugins/saml/SamlSecurityRealm.java, src/main/java/org/jenkinsci/plugins/saml/SamlUserDetails.java, src/main/java/org/jenkinsci/plugins/saml/SamlUserDetailsService.java
Some log improvements and Jenkins core version fixed to 1.642.4
=> [JENKINS-39601] Improve log

src/main/java/org/jenkinsci/plugins/saml/SamlEncryptionData.java, src/main/java/org/jenkinsci/plugins/saml/SamlSecurityRealm.java
some changes suggested by @benmccann
=> Improve log

src/main/java/org/jenkinsci/plugins/saml/SamlUserDetailsService.java
Loading existing user by name should not be creating new users.
Therefore, the User lookup method is updated to disable automatic
creation of users.
@reviewbybees please
=> JENKINS-38228 - User lookup method is changed in Details Services.

src/main/java/org/jenkinsci/plugins/saml/SamlLogoutAction.java, src/main/java/org/jenkinsci/plugins/saml/SamlSecurityRealm.java, src/main/resources/org.jenkinsci.plugins.saml.SamlLogoutAction/index.jelly
@reviewbybees 
I based my code on https://github.com/jenkinsci/github-oauth-plugin/pull/58/files
=> [FIX JENKINS-37311] make the logout button works

src/main/java/org/jenkinsci/plugins/saml/SamlGroupDetails.java, src/main/java/org/jenkinsci/plugins/saml/SamlSecurityRealm.java, src/main/java/org/jenkinsci/plugins/saml/user/LoginDetailsProperty.java, src/main/resources/org/jenkinsci/plugins/saml/user/LoginDetailsProperty/config.jelly
@reviewbybees 
it allow identifying groups that have users as external groups
it uses the granted authorities to identify external groups
=> [JENKINS-43939] Complete the implementation of SecurityRealm

pom.xml, src/test/java/org/jenkinsci/plugins/saml/SamlSecurityRealmTest.java, src/test/resources/org/jenkinsci/plugins/saml/SamlSecurityRealmTest/metadataWrapper/metadata.xml
[JENKINS-45975](https://issues.jenkins-ci.org/browse/JENKINS-45975)
This is the only unit test I could add (all other wrappers depend on `StaplerRequest` incoming data). However the code is covered by [the ATH](https://github.com/jenkinsci/acceptance-test-harness/blob/master/src/test/java/plugins/SAMLPluginTest.java).
@reviewbybees esp. @kuisathaverat
=> [JENKINS-45975] Unit test for SamlSPMetadataWrapper

src/main/java/org/jenkinsci/plugins/saml/OpenSAMLWrapper.java, src/main/java/org/jenkinsci/plugins/saml/SamlEncryptionData.java, src/main/java/org/jenkinsci/plugins/saml/SamlSecurityRealm.java, src/main/resources/org/jenkinsci/plugins/saml/SamlSecurityRealm/config.jelly, src/test/java/org/jenkinsci/plugins/saml/SamlFormValidationsTest.java, src/test/java/org/jenkinsci/plugins/saml/SamlSecurityRealmTest.java, src/test/resources/org/jenkinsci/plugins/saml/SamlSecurityRealmTest/testReadSimpleConfigurationEncryptionData/config.xml
[JENKINS-46007](https://issues.jenkins-ci.org/browse/JENKINS-46007)
Supersedes #31.
@reviewbybees esp. @amuniz
=> [JENKINS-46007] Use Secret to store keystore & storepass for SamlEncryptionData

pom.xml
[JENKINS-46949](https://issues.jenkins-ci.org/browse/JENKINS-46949)
@reviewbybees @kuisathaverat
=> [JENKINS-46949] Downgrade bouncycastle-api

README.md, src/main/java/org/jenkinsci/plugins/saml/OpenSAMLWrapper.java, src/main/java/org/jenkinsci/plugins/saml/SamlAdvancedConfiguration.java, src/main/java/org/jenkinsci/plugins/saml/SamlPluginConfig.java, src/main/java/org/jenkinsci/plugins/saml/SamlSecurityRealm.java, src/main/resources/org/jenkinsci/plugins/saml/SamlSecurityRealm/config.jelly, src/main/webapp/help/binding.html, src/test/java/org/jenkinsci/plugins/saml/OpenSamlWrapperTest.java, src/test/java/org/jenkinsci/plugins/saml/SamlSecurityRealmTest.java, src/test/resources/org/jenkinsci/plugins/saml/SamlSecurityRealmTest/testReadSimpleConfigurationHTTPPost/config.xml
[JENKINS-45857](https://issues.jenkins-ci.org/browse/JENKINS-45857)
It adds a new setting to select the binding method if it's not selected or it's an old configuration the default value is HTTP-Redirect.
@reviewbybees
=> [FIX JENKINS-45857] Support to set the Binding type (Redirection/Post)

src/main/java/org/jenkinsci/plugins/saml/IdpMetadataConfiguration.java, src/main/java/org/jenkinsci/plugins/saml/UpdateMetadataFromURLPeriodicWork.java
[JENKINS-49239](https://issues.jenkins-ci.org/browse/JENKINS-49239)
@reviewbybees
=> [JENKINS-49239] Periodic work running with URL empty

doc/CONFIGURE.md, src/main/java/org/jenkinsci/plugins/saml/OpenSAMLWrapper.java, src/main/java/org/jenkinsci/plugins/saml/SamlEncryptionData.java, src/main/resources/org/jenkinsci/plugins/saml/SamlEncryptionData/config.jelly, src/main/webapp/help/forceSignRedirectBindingAuthnRequest.html, src/test/java/org/jenkinsci/plugins/saml/SamlSecurityRealmTest.java
[JENKINS-47966](https://issues.jenkins-ci.org/browse/JENKINS-47966)
* It Adds an option to disable the signing in HTTP-Redirect bindings
@reviewbybees
=> [JENKINS-47966] Add option to disable request signature in saml plugin

src/main/java/org/jenkinsci/plugins/saml/SamlSecurityRealm.java, src/main/java/org/jenkinsci/plugins/saml/conf/Attribute.java, src/main/java/org/jenkinsci/plugins/saml/conf/AttributeEntry.java, src/main/java/org/jenkinsci/plugins/saml/user/SamlCustomProperty.java, src/main/resources/org/jenkinsci/plugins/saml/SamlSecurityRealm/config.jelly, src/main/resources/org/jenkinsci/plugins/saml/conf/Attribute/config.jelly, src/main/resources/org/jenkinsci/plugins/saml/user/SamlCustomProperty/config.jelly, src/main/webapp/help/customAttributes.html, src/test/java/org/jenkinsci/plugins/saml/OpenSamlWrapperTest.java
[JENKINS-45437](https://issues.jenkins-ci.org/browse/JENKINS-45437)
* Read attributes from SAML Response and show them in the User Profile
=> [JENKINS-45437] load SAML custom attributes

Jenkinsfile, pom.xml, src/main/java/org/jenkinsci/plugins/saml/OpenSAMLWrapper.java, src/main/java/org/jenkinsci/plugins/saml/SamlAuthenticationToken.java, src/main/java/org/jenkinsci/plugins/saml/SamlCrumbExclusion.java, src/main/java/org/jenkinsci/plugins/saml/SamlUserDetails.java
Just minor updates while I was around. The change enables testing for JEP-200 just in case a regression gets introduced
@reviewbybees @kuisathaverat
=> Test the plugin against 2.107.2

pom.xml, src/main/java/org/jenkinsci/plugins/saml/BundleKeyStore.java, src/main/java/org/jenkinsci/plugins/saml/SamlAuthenticationToken.java, src/main/java/org/jenkinsci/plugins/saml/SamlSecurityRealm.java, src/main/java/org/jenkinsci/plugins/saml/SamlValidateIdPMetadata.java, src/test/java/org/jenkinsci/plugins/saml/SamlSecurityRealmTest.java
[JENKINS-55205](https://issues.jenkins-ci.org/browse/JENKINS-55205)
* fix some findbugs
* update Jenkins core version
* update pom plugin version
=> [JENKINS-55205] fix some findbugs

src/main/java/org/jenkinsci/plugins/saml/IdpMetadataConfiguration.java, src/main/java/org/jenkinsci/plugins/saml/SamlAuthenticationToken.java, src/main/java/org/jenkinsci/plugins/saml/SamlEncryptionData.java, src/main/java/org/jenkinsci/plugins/saml/SamlGroupDetails.java, src/main/java/org/jenkinsci/plugins/saml/SamlSecurityRealm.java
Did some scan with SonarLint and fixed some upcomming issues, there. Hope you agree with it.
=> Fixed some parts after SonarLint scan

doc/TROUBLESHOOTING.md
Changes 'defaulr' to 'default'
=> Spelling update TROUBLESHOOTING.md

doc/TROUBLESHOOTING.md, src/main/java/org/jenkinsci/plugins/saml/BundleKeyStore.java
* add a more explanatory message
* add the fail to the troubleshooting guide
=> [JENKINS-58138] Confusing saml plugin keystore breakage

pom.xml
see [JENKINS-59146](https://issues.jenkins-ci.org/browse/JENKINS-59146)
=> [JENKINS-59146] bump plugin dependencies and core

pom.xml, src/test/java/org/jenkinsci/plugins/saml/SamlJCasCCompatibilityTest.java
https://github.com/jenkinsci/configuration-as-code-plugin/pull/1049
=> fix space in expected log

src/main/java/org/jenkinsci/plugins/saml/OpenSAMLWrapper.java, src/main/java/org/jenkinsci/plugins/saml/SAML2ClientConfigurationCustom.java, src/main/java/org/jenkinsci/plugins/saml/SamlEncryptionData.java, src/main/java/org/jenkinsci/plugins/saml/SamlSecurityRealm.java, src/main/resources/org/jenkinsci/plugins/saml/SamlEncryptionData/config.jelly, src/main/webapp/help/forceSignRedirectBindingAuthnRequest.html, src/test/java/org/jenkinsci/plugins/saml/OpenSamlWrapperTest.java, src/test/java/org/jenkinsci/plugins/saml/SamlFormValidationsTest.java
see [JENKINS-47640](https://issues.jenkins-ci.org/browse/JENKINS-47640)
Allow disabling Auth request signature on HTTP-POST request
=> [JENKINS-47640] Allow to disable Request signature on HTTP-POST request

src/main/java/org/jenkinsci/plugins/saml/SamlSecurityRealm.java
See [JENKINS-60095](https://issues.jenkins-ci.org/browse/JENKINS-60095).
=> Handle windows paths

doc/CONFIGURE.md, doc/TROUBLESHOOTING.md, src/main/webapp/help/metadata.html
Update documentation about metadata and some SAML terms
=> docs: Update documentation about metadata and some SAML terms

Jenkinsfile, doc/CONFIGURE.md, src/main/java/org/jenkinsci/plugins/saml/OpenSAMLWrapper.java, src/main/java/org/jenkinsci/plugins/saml/SamlEncryptionData.java, src/main/resources/org/jenkinsci/plugins/saml/SamlEncryptionData/config.jelly, src/main/webapp/help/wantsAssertionsSigned.html, src/test/java/org/jenkinsci/plugins/saml/LiveTest.java, src/test/java/org/jenkinsci/plugins/saml/OpenSamlWrapperTest.java, src/test/java/org/jenkinsci/plugins/saml/SamlSecurityRealmTest.java
See [JENKINS-65039](https://issues.jenkins-ci.org/browse/JENKINS-65039).
it adds a setting to allow disable the Assertion signature request.
=> [JENKINS-65039] Wants assertions signed by default false

src/main/java/org/jenkinsci/plugins/saml/SamlSecurityRealm.java
See [JENKINS-65093](https://issues.jenkins-ci.org/browse/JENKINS-65093).
=> [JENKINS-65093] normalize the way to manage attibutes as list<String>

pom.xml
=> Bump apache httpcomponents to 4.5.13

src/main/java/org/jenkinsci/plugins/saml/user/LoginDetailsProperty.java, src/main/java/org/jenkinsci/plugins/saml/user/SamlCustomProperty.java
See [JENKINS-XXXXX](https://issues.jenkins-ci.org/browse/JENKINS-XXXXX).
=> Only enable SAML UserProperties when SAML security realm is used.

src/main/java/org/jenkinsci/plugins/saml/SamlSecurityRealm.java, src/test/java/org/jenkinsci/plugins/saml/SamlSecurityRealmTest.java, src/test/resources/org/jenkinsci/plugins/saml/SamlSecurityRealmTest/samlProfileWithEmptyGroups/config.xml
See [JENKINS-66007](https://issues.jenkins-ci.org/browse/JENKINS-66007).
=> [JENKINS-66007] Filter out empty groups from the saml profile and issue a warning

pom.xml, src/main/java/org/jenkinsci/plugins/saml/SamlCrumbExclusion.java, src/test/java/org/jenkinsci/plugins/saml/FakeRequest.java, src/test/java/org/jenkinsci/plugins/saml/SamlCrumbExclusionTest.java, src/test/resources/org/jenkinsci/plugins/saml/SamlCrumbExclusionTest/testReadSimpleConfiguration/config.xml
https://www.jenkins.io/security/advisory/2021-08-31/#SECURITY-2469
This PR should be merged using merge commit (on GH or git CLI), not rebase or squash, so that the release commits are part of the default branch history.
=> Integrate 2.0.8 security update

Jenkinsfile, pom.xml, src/main/java/org/jenkinsci/plugins/saml/SamlSecurityRealm.java, src/test/resources/org/jenkinsci/plugins/saml/LiveTest/docker-compose.yml
It updates the Jenkins Core to 2.289
=> chore: bump Jenkins core to 2.289

Jenkinsfile, pom.xml
* bump Jenkins core to 2.303.3
* update Jenkinsfile to use defaults
=> chore: bump Jenkins core to 2.303.3

.github/dependabot.yml, .github/release-drafter.yml, .github/workflows/cd.yaml, .mvn/maven.config, pom.xml
This comes with a new version number format, see https://www.jenkins.io/jep/229
=> feat: enable continuous delivery

Jenkinsfile, README.md
Basically checking against:
* https://github.com/jenkinsci/jenkins/pull/5707
* https://github.com/jenkinsci/jenkins/pull/5858
=> Verify the version past the Guava & Guice bumps

pom.xml
chore: change the version number format
=> chore: change version number format

pom.xml
A release of this would help us do Java 17 testing of this plugin. CC @kuisathaverat
=> Bump parent POM from 4.37 to 4.38

pom.xml
Cleans up some technical debt added by me in an earlier PR.
=> Clean up TODO

.gitignore, pom.xml
Since this PR the compatibility with Java 8 is not guaranteed and is not supported.
* fix: remove deprecated java.level property
* feat: bump Jenkins core to 2.361
=> feat: Remove support for Java 8

pom.xml, src/main/resources/org/jenkinsci/plugins/saml/SamlSecurityRealm/config.jelly
* Downstream of https://github.com/jenkinsci/jenkins/pull/6615
To be merged whenever this plugin decides to depend on a Jenkins Core 2.351 or later.
=> Use optionalProperty from core

CHANGELOG.md, doc/ADFS_CONFIG.md, doc/CONFIGURE.md, doc/CONFIGURE_AZURE.md, doc/TROUBLESHOOTING.md, src/main/resources/org/jenkinsci/plugins/saml/SamlLogoutAction/index.jelly, src/main/resources/org/jenkinsci/plugins/saml/user/LoginDetailsProperty/config.jelly, src/main/resources/org/jenkinsci/plugins/saml/user/SamlCustomProperty/config.jelly, src/main/webapp/help/forceSignRedirectBindingAuthnRequest.html, src/main/webapp/help/usernameCaseConversion.html, src/test/resources/org/jenkinsci/plugins/saml/SamlCrumbExclusionTest/testReadSimpleConfiguration/config.xml, src/test/resources/org/jenkinsci/plugins/saml/SamlFormValidationsTest/testReadSimpleConfigurationAdvancedConfiguration/config.xml, src/test/resources/org/jenkinsci/plugins/saml/SamlSecurityRealmTest/samlProfileWithEmptyGroups/config.xml, src/test/resources/org/jenkinsci/plugins/saml/SamlSecurityRealmTest/testHugeNumberOfUsers/config.xml, src/test/resources/org/jenkinsci/plugins/saml/SamlSecurityRealmTest/testReadSimpleConfiguration/config.xml, src/test/resources/org/jenkinsci/plugins/saml/SamlSecurityRealmTest/testReadSimpleConfigurationAdvancedConfiguration/config.xml, src/test/resources/org/jenkinsci/plugins/saml/SamlSecurityRealmTest/testReadSimpleConfigurationEncryptionData/config.xml, src/test/resources/org/jenkinsci/plugins/saml/SamlSecurityRealmTest/testReadSimpleConfigurationEncryptionData1/config.xml, src/test/resources/org/jenkinsci/plugins/saml/SamlSecurityRealmTest/testReadSimpleConfigurationHTTPPost/config.xml, src/test/resources/org/jenkinsci/plugins/saml/SamlSecurityRealmTest/testReadSimpleConfigurationLowercase/config.xml, src/test/resources/org/jenkinsci/plugins/saml/SamlSecurityRealmTest/testReadSimpleConfigurationUppercase/config.xml, src/test/resources/org/jenkinsci/plugins/saml/SamlSecurityRealmTest/upgradeIDPMetadataFileTest/config.xml
* docs: fix typos and grammar
* chore: remove unused namespaces on jelly files
* chore: use one tag for empty tags on HTML
=> docs: fix typos and grammar

src/main/java/org/jenkinsci/plugins/saml/BundleKeyStore.java, src/main/java/org/jenkinsci/plugins/saml/IdpMetadataConfiguration.java, src/main/java/org/jenkinsci/plugins/saml/OpenSAMLWrapper.java, src/main/java/org/jenkinsci/plugins/saml/SamlCrumbExclusion.java, src/main/java/org/jenkinsci/plugins/saml/SamlFileResource.java, src/main/java/org/jenkinsci/plugins/saml/SamlFormValidation.java, src/main/java/org/jenkinsci/plugins/saml/SamlPluginConfig.java, src/main/java/org/jenkinsci/plugins/saml/SamlProfileWrapper.java, src/main/java/org/jenkinsci/plugins/saml/SamlRedirectActionWrapper.java, src/main/java/org/jenkinsci/plugins/saml/SamlSPMetadataWrapper.java, src/main/java/org/jenkinsci/plugins/saml/SamlValidateIdPMetadata.java, src/main/java/org/jenkinsci/plugins/saml/UpdateMetadataFromURLPeriodicWork.java, src/main/java/org/jenkinsci/plugins/saml/conf/Attribute.java, src/main/java/org/jenkinsci/plugins/saml/user/SamlCustomProperty.java, src/test/java/org/jenkinsci/plugins/saml/FakeRequest.java, src/test/java/org/jenkinsci/plugins/saml/OpenSamlWrapperTest.java, src/test/java/org/jenkinsci/plugins/saml/SamlCrumbExclusionTest.java, src/test/java/org/jenkinsci/plugins/saml/SamlFormValidationsTest.java
this PR fix some code warning, remove some deprecations, and move some code to Java 11 syntax, there are no changes in funcionality or implementation.
=> fix: code warnings

doc/TROUBLESHOOTING.md
… 
See [JENKINS-69416](https://issues.jenkins-ci.org/browse/JENKINS-69416).
=> docs: troubleshooting for 'HTTP ERROR 403 No valid crumb was included in the request' errors

src/test/java/org/jenkinsci/plugins/saml/LiveTest.java
Since https://github.com/jenkinsci/jenkins-test-harness/pull/475 & https://github.com/jenkinsci/jenkins-test-harness/pull/348, you need to call `RealJenkinsRule#getUrl` after starting Jenkins.
=> Fix `LiveTest`

doc/CONFIGURE_AZURE.md
Add the generic sign out URL for Azure AD
=> docs: add Sign Out URL

src/main/java/org/jenkinsci/plugins/saml/IdpMetadataConfiguration.java, src/main/java/org/jenkinsci/plugins/saml/SamlAdvancedConfiguration.java, src/main/java/org/jenkinsci/plugins/saml/SamlEncryptionData.java, src/main/java/org/jenkinsci/plugins/saml/SamlSecurityRealm.java
fix: Stapler: Missing POST/RequirePOST annotation
=> fix: Stapler: Missing POST/RequirePOST annotation

src/main/java/org/jenkinsci/plugins/saml/IdpMetadataConfiguration.java, src/main/java/org/jenkinsci/plugins/saml/SamlAdvancedConfiguration.java, src/main/java/org/jenkinsci/plugins/saml/SamlEncryptionData.java, src/main/java/org/jenkinsci/plugins/saml/SamlSecurityRealm.java
fix: Stapler: Missing permission check
=> fix: Stapler: Missing permission check

src/main/java/org/jenkinsci/plugins/saml/SamlSecurityRealm.java
See [JENKINS-69932](https://issues.jenkins-ci.org/browse/JENKINS-69932).
=> [JENKINS-69932] Log in: This URL requires POST

src/main/java/org/jenkinsci/plugins/saml/SamlSecurityRealm.java
See [JENKINS-69959](https://issues.jenkins.io/browse/JENKINS-69959).
- #277 
- #278
=> fix: metadata endpoint should be public

doc/CONFIGURE.md, src/main/java/org/jenkinsci/plugins/saml/OpenSAMLWrapper.java, src/main/java/org/jenkinsci/plugins/saml/SamlAdvancedConfiguration.java, src/main/resources/org/jenkinsci/plugins/saml/SamlAdvancedConfiguration/config.jelly, src/main/webapp/help/randomRelayState.html, src/test/java/org/jenkinsci/plugins/saml/LiveTest.java
It adds support to use a random value for the relayState SAML parameter
=> feat: support random generated relayState parameter

src/main/java/org/jenkinsci/plugins/saml/IdpMetadataConfiguration.java, src/main/java/org/jenkinsci/plugins/saml/SamlAuthenticationToken.java, src/main/java/org/jenkinsci/plugins/saml/SamlEncryptionData.java, src/main/java/org/jenkinsci/plugins/saml/SamlFileResource.java, src/main/java/org/jenkinsci/plugins/saml/SamlFileResourceCache.java, src/main/java/org/jenkinsci/plugins/saml/SamlFileResourceDisk.java, src/main/java/org/jenkinsci/plugins/saml/SamlSecurityRealm.java, src/main/java/org/jenkinsci/plugins/saml/SamlUserDetails.java, src/main/java/org/jenkinsci/plugins/saml/SamlUserDetailsService.java, src/main/java/org/jenkinsci/plugins/saml/user/LoginDetailsProperty.java
Several years ago, Jenkins core switched from the abandoned JSR 305 annotations to SpotBugs annotations, but this plugin never caught up. This PR adapts this plugin to the common convention used in Jenkins core and the vast majority of other Jenkins plugins.
=> EOL JSR 305

src/main/java/org/jenkinsci/plugins/saml/SamlSecurityRealm.java
See [JENKINS-71322](https://issues.jenkins-ci.org/browse/JENKINS-71322).
=> [JENKINS-71322] NPE on non existing SAML Attribute

doc/CONFIGURE.md, doc/CONFIGURE_KEYCLOAK.md, doc/TROUBLESHOOTING.md
* Also adjust heading levels in Troubleshooting,
* and document the "NameIDPolicy Format" field
Previously requested in [JENKINS-49608](https://issues.jenkins.io/browse/JENKINS-49608).
[Docker - Keycloak Getting started guide](https://www.keycloak.org/getting-started/getting-started-docker) is what I used to get a test Keycloak server with basic config.
I tested with 4.418.vdfa_7489a_b_a_2d, not the main branch.
=> Add documentation for the Keycloak

doc/CONFIGURE.md
Use similar formatting and method of writing for all path-like items. Helps with visibility when reading the rendered markdown. Add asterisk to each item of list to make viewable as a list.
=> Align formatting of paths

pom.xml
=> Upgrade plugin parent POM to latest

doc/TROUBLESHOOTING.md
see https://issues.jenkins.io/browse/JENKINS-73751
=> docs: [JENKINS-73751] Redirecting to Base URL Rather than Original Requested URL

src/main/java/org/jenkinsci/plugins/saml/SamlFileResource.java, src/main/java/org/jenkinsci/plugins/saml/SamlFileResourceCache.java, src/main/java/org/jenkinsci/plugins/saml/SamlFileResourceDisk.java
See [JENKINS-73816](https://issues.jenkins-ci.org/browse/JENKINS-73816).
=> fix: [JENKINS-73816] implement missing methods

src/main/java/org/jenkinsci/plugins/saml/SamlProfileWrapper.java, src/main/java/org/jenkinsci/plugins/saml/SamlRedirectActionWrapper.java, src/main/java/org/jenkinsci/plugins/saml/SamlSPMetadataWrapper.java
Enclose the SAML2Client in a try to make use the Closeable implementation.
=> fix: JENKINS-53245 use closeable

pom.xml, src/test/java/org/jenkinsci/plugins/saml/OpenSamlWrapperTest.java, src/test/java/org/jenkinsci/plugins/saml/SamlCrumbExclusionTest.java, src/test/java/org/jenkinsci/plugins/saml/SamlFileResourceTest.java, src/test/java/org/jenkinsci/plugins/saml/SamlFormValidationsTest.java, src/test/java/org/jenkinsci/plugins/saml/SamlJCasCCompatibilityTest.java, src/test/java/org/jenkinsci/plugins/saml/SamlSecurityRealmTest.java
This PR aims to migrate tests to JUnit5. Changes include:
* Migrate annotations and imports
* Migrate assertions
* Remove public visibility for test classes and methods
* Minor clean up
I did not migrate `LiveTest` as it is using `RealJenkinsRule` for which there is no JUnit5 equivalent yet.
I am well aware that this is a quite large changeset however I hope that there is still interest in this PR and it will be reviewed.
If there are any questions, please do not hesitate to ping me.
=> Migrate tests to JUnit5

src/main/java/org/jenkinsci/plugins/saml/SamlSecurityRealm.java
https://issues.jenkins.io/browse/JENKINS-75665
=> [JENKINS-75665] Using serializable SecurityContext
