- .gitignore
- src/main/java/org/jenkinsci/plugins/saml/SamlGroupAuthority.java
- src/main/java/org/jenkinsci/plugins/saml/SamlSecurityRealm.java
- src/main/java/org/jenkinsci/plugins/saml/SamlUserDetails.java
- src/main/java/org/jenkinsci/plugins/saml/SamlUserDetailsService.java
- src/main/resources/org/jenkinsci/plugins/saml/SamlSecurityRealm/config.jelly
- src/main/webapp/help/displayNameAttributeName.html
- src/main/webapp/help/groupsAttributeName.html
- src/main/webapp/help/maximumAuthenticationLifetime.html
- src/main/webapp/help/metadata.html
There several changes were made
* Groups support added (works in conjunction with [Role-based Authorization Strategy](https://wiki.jenkins-ci.org/display/JENKINS/Role+Strategy+Plugin))
* Added ability to send user full name as a separate claim (user full name will be updated if attribute received and its value is not equal to current value)
* Plugin configuration extended, added settings for 
* Groups attribute name
* User full name attribute name
* Token maximum lifetime (without this setting plugin might begin to fall due to authentication session expiration with certain settings of IdP)
* Added support for showing Groups on user's info page (works only for users with admin rights)
> Groups support for saml-plugin (2nd attempt)

- src/main/java/org/jenkinsci/plugins/saml/SamlCrumbExclusion.java
- src/main/java/org/jenkinsci/plugins/saml/SamlSecurityRealm.java
It's not possible to use the SAML plugin along with the CSRF protection built in to Jenkins.  This is because the auth redirect that goes back to Jenkins doesn't contain the protection crumb.  Since it would be difficult to force an auth, it makes sense to remove the CSRF protection from that endpoint in particular.  That is what this pull request does.
> add CSRF exclusion for the finishLogin url

- src/main/java/org/jenkinsci/plugins/saml/SamlSecurityRealm.java
- src/main/resources/org/jenkinsci/plugins/saml/SamlSecurityRealm/config.jelly
- src/main/webapp/help/usernameCaseConversion.html
[JENKINS-29086] Work-around for handling SAML user id case sensitivity : provide option to convert returned value to a specific case.
> [JENKINS-29086] Work-around for handling case sensitivity

- pom.xml
- src/main/java/org/jenkinsci/plugins/saml/SamlEncryptionData.java
- src/main/java/org/jenkinsci/plugins/saml/SamlSecurityRealm.java
- src/main/resources/org/jenkinsci/plugins/saml/SamlSecurityRealm/config.jelly
- src/main/webapp/help/encryption.html
- src/main/webapp/help/keyPassword.html
- src/main/webapp/help/keystorePassword.html
- src/main/webapp/help/keystorePath.html
- src/main/webapp/help/usernameAttributeName.html
In order to get the plugin to authenticate nicely with a Shibboleth IdP, I needed a couple of configuration items:
- an SSL key pair.  
- the ability to configure an attribute to be used as the username rather than the nameID.  
It's also very useful to be able to access the SP metadata in order to configure the IdP.  This pull request implements these changes.
The link to access the metadata is a bit clunky - it would be nice if this was a copyButton, but I couldn't see how to make its contents dynamic.
> More SAML configuration options

- src/main/java/org/jenkinsci/plugins/saml/SamlSecurityRealm.java
`maximumAuthenticationLifetime` setting had no effect, because client is initialised in `printClientMetadata` method and after init changing `maximumAuthenticationLifetime` has no effect.
> Fix maximum authentication lifetime setting

- src/main/java/org/jenkinsci/plugins/saml/SamlSecurityRealm.java
- src/main/java/org/jenkinsci/plugins/saml/user/LoginDetailsProperty.java
- src/main/resources/org/jenkinsci/plugins/saml/user/LoginDetailsProperty/config.jelly
fire loggedIn event when the user is logged to save the jenkins.security.LastGrantedAuthoritiesProperty this allow the plugin to restore authorities when you access by API token
also, I add a new user property to save creation date, last login, and a login counter
@reviewbybees
> [JENKINS-38034] SAML Plugin does not load groups when access with API Token

- src/main/java/org/jenkinsci/plugins/saml/BundleKeyStore.java
[JENKINS-46181](https://issues.jenkins-ci.org/browse/JENKINS-46181)
also, the posibility of set the value with a property -Dorg.jenkinsci.plugins.saml.BundleKeyStore.validity=VALUE_IN_DAYS
> [FIX JENKINS-46181] Changes default validity of the generated key to 365 days

- README.md
- src/main/java/org/jenkinsci/plugins/saml/SamlSecurityRealm.java
[JENKINS-47850](https://issues.jenkins-ci.org/browse/JENKINS-47850)
* Logs the SAMLResponse even it is not valid
* Protect against [JDK-8176043](https://bugs.openjdk.java.net/browse/JDK-8176043)
```
Caused by: java.lang.IllegalArgumentException: Illegal base64 character d
at java.util.Base64$Decoder.decode0(Base64.java:714)
at java.util.Base64$Decoder.decode(Base64.java:526)
at java.util.Base64$Decoder.decode(Base64.java:549)
at org.jenkinsci.plugins.saml.SamlSecurityRealm.doFinishLogin(SamlSecurityRealm.java:258)
```
@reviewbybees
> [JENKINS-47850] log SAMLResponse on encoding errors

- src/main/java/org/jenkinsci/plugins/saml/BundleKeyStore.java
[JENKINS-49532](https://issues.jenkins-ci.org/browse/JENKINS-49532)
@reviewbybees
> [JENKINS-49532] autogenerated keystore should not be kept in temp directory

- src/main/java/org/jenkinsci/plugins/saml/UpdateMetadataFromURLPeriodicWork.java
[JENKINS-53487](https://issues.jenkins-ci.org/browse/JENKINS-53487)
* New property to set the initial delay
* Use getInitialDelay to get the time of the first launch
> [JENKINS-53487] change to use initial delay

- src/main/webapp/help/maximumSessionLifetime.html
Jenkins uses jetty which has a default http session timeout of 30min (https://stackoverflow.com/q/26407541). Should mention in the help that this is relevant to saml auth.
> improve session lifetime help

- Jenkinsfile
- pom.xml
https://issues.jenkins-ci.org/browse/JENKINS-55175
Requires https://github.com/jenkinsci/plugin-pom/pull/141 to be released first
@jenkinsci/java11-support
> [JENKINS-55175] - Use Mockito from Plugin POM to support testing with Java 11

- pom.xml
- src/test/java/org/jenkinsci/plugins/saml/SamlJCasCCompatibilityTest.java
- src/test/resources/org/jenkinsci/plugins/saml/configuration-as-code.yaml
See [JENKINS-59126](https://issues.jenkins-ci.org/browse/JENKINS-59126)
So far, _saml-plugin_ is compatible with JCasC and can be both exported and configured using that plugin. This PR adds a compatibility test so any future incompatibility can be detected in advance in such way as other plugins:
- [ant-plugin](https://github.com/jenkinsci/ant-plugin/blob/master/src/test/java/hudson/tasks/AntJCasCCompatibilityTest.java)
- [git-plugin](https://github.com/jenkinsci/git-plugin/blob/master/src/test/java/jenkins/plugins/git/GitJCasCCompatibilityTest.java)
- [antisamy-markup-formatter-plugin](https://github.com/jenkinsci/antisamy-markup-formatter-plugin/blob/master/src/test/java/hudson/markup/JCasCCompatibilityTest.java)
See below the config.xml configured by UI, the jenkins.yaml with the …
> [JENKINS-59126] Add compatibility test with JCasC

- src/main/java/org/jenkinsci/plugins/saml/OpenSAMLWrapper.java
- src/main/java/org/jenkinsci/plugins/saml/SamlAdvancedConfiguration.java
- src/main/java/org/jenkinsci/plugins/saml/SamlPluginConfig.java
- src/main/resources/org/jenkinsci/plugins/saml/SamlAdvancedConfiguration/config.jelly
- src/main/webapp/help/nameIdPolicyFormat.html
- src/test/java/org/jenkinsci/plugins/saml/SamlSecurityRealmTest.java
This was needed to work with ADFS (v2).
Adding the NameIDPolicy in the AuthnRequest sent from the SP to the Idp.
> [JENKINS-59097] Possibility to set NameIDPolicy in the SAML Request 

- doc/CONFIGURE.md
- src/main/resources/org/jenkinsci/plugins/saml/SamlEncryptionData/config.jelly
- src/main/webapp/help/forceSignRedirectBindingAuthnRequest.html
See [JENKINS-59818](https://issues.jenkins-ci.org/browse/JENKINS-59818).
the flag was always inverted, it would not be detected because it does not apply on some configuration until now. This PR update the field description, help, and documentation related to describe the correct behavior of the setting.
> [JENKINS-59818] Mangement of 'Disable Auth Request Signature' flag is inverted

- pom.xml
See [JENKINS-60679](https://issues.jenkins-ci.org/browse/JENKINS-60679).
Update BouncyCastle to 2.18 causes the following exception on SAML Plugin 1.14, so we have to bump the BouncyCastle to 2.18.
```
java.lang.NoSuchMethodError: org.bouncycastle.asn1.DERNull.equals(Lorg/bouncycastle/asn1/ASN1Encodable;)Z
at org.bouncycastle.operator.jcajce.OperatorHelper.getSignatureName(Unknown Source)
at org.bouncycastle.operator.jcajce.OperatorHelper.createSignature(Unknown Source)
at org.bouncycastle.operator.jcajce.JcaContentSignerBuilder.build(Unknown Source)
at org.jenkinsci.plugins.saml.BundleKeyStore.generateCertificate(BundleKeyStore.java:279)
at org.jenkinsci.plugins.saml.BundleKeyStore.createCertificateChain(BundleKeyStore.java:151)
at …
```
> [JENKINS-60679] Bump bouncycastle api plugin due NoSuchMethodError exception

- Jenkinsfile
- pom.xml
See [JENKINS-60742](https://issues.jenkins-ci.org/browse/JENKINS-60742).
> [JENKINS-60742] Bump core to 2.176.1 version and bump plugin dependecies

- pom.xml
Updating a potential denial of service issue in cryptacular
Updating pac4j to 3.8.2 to pull in changes requires a major rewrite of the plugin
configured  dependency management for cryptaclur to 1.2.4 to resolve CVE-2020-7226. 
See [JENKINS-XXXXX](https://issues.jenkins-ci.org/browse/JENKINS-XXXXX).
@kuisathaverat  let me know if you want a Jenkins Issue for this.
> Update cryptacular to 1.2.4 

- doc/CONFIGURE.md
- doc/TROUBLESHOOTING.md
- src/main/webapp/help/forceSignRedirectBindingAuthnRequest.html
See [JENKINS-61917](https://issues.jenkins-ci.org/browse/JENKINS-61917).
documenting that disabling signature is not supported on redirect binding
> docs: documenting that disabling signature is not supported on redirect binding

- pom.xml
Resolves [CVE-2019-12400](https://github.com/advisories/GHSA-4q98-wr72-h35w).
Smoke test passed using https://capriza.github.io/samling/samling.html.
> org.apache.sanctuario:xmlsec --> 2.1.4

- doc/ADFS_CONFIG.md
Seems like https://github.com/jenkinsci/saml-plugin/pull/89 has changed some behaviour w.r.t Base64 encoding, and ADFS doesn't like seeing line breaks and complains.
/cc @schottsfired
> Document that a system property is required for ADFS

- src/main/java/org/jenkinsci/plugins/saml/OpenSAMLWrapper.java
- src/main/java/org/jenkinsci/plugins/saml/SamlProfileWrapper.java
- src/main/java/org/jenkinsci/plugins/saml/SamlRedirectActionWrapper.java
- src/main/java/org/jenkinsci/plugins/saml/SamlSPMetadataWrapper.java
See [JENKINS-65513](https://issues.jenkins-ci.org/browse/JENKINS-65513).
For some reason now it needs to destroy the SAMLClient to avoid keep a couple of classes running on each creation.
> [JENKINS-65513] Saml plugin 2.x.x causes deadlock impacting Jenkins performance

- src/main/java/org/jenkinsci/plugins/saml/SamlUserDetailsService.java
Since this method doesn't actually check the IDP, it is only relying on
whether the user has already logged in to Jenkins. If not, then it
cannot tell whether the user actually exists or not.
See [JENKINS-67574](https://issues.jenkins-ci.org/browse/JENKINS-67574).
I actually don't have a working saml setup so this needs manual testing that the described issue is actually fixed by this patch.
> [JENKINS-67574] `loadUserByUsername` should throw `UserMayOrMayNotExistException2` if the user doesn't exist in Jenkins

- pom.xml
See [JENKINS-68471](https://issues.jenkins-ci.org/browse/JENKINS-68471). This plugin depends on `org.pac4j:pac4j-saml`, which depends on `org.pac4j:pac4j-saml`, which depends on `org.opensaml:opensaml-security-api`, which depends on `org.apache.santuario:xmlsec`, which depends on JAXB:
```
org.jenkins-ci.plugins:saml:hpi:2.999999-SNAPSHOT
+- org.pac4j:pac4j-saml:jar:3.9.0:compile
|  +- org.opensaml:opensaml-security-api:jar:3.4.3:compile
|  |  +- org.apache.santuario:xmlsec:jar:2.3.0:compile
|  |  |  +- JAXB
```
But when running on Java 9+, JAXB is not included on the classpath by default. The only way for a plugin to have access to JAXB when running on Jenkins 2.164 or later on Java 11 is to declare a plugin-to-plugin dependency on JAXB API plugin (recommended) or to embed JAXB into its …
> [JENKINS-68471] Prepare SAML for removal of JAXB and Java 11 requirement

- src/main/resources/org/jenkinsci/plugins/saml/SamlSecurityRealm/config.jelly
On Jenkins 2.346 and later the new UI layout breaks with the current way this plugin uses optional properties. The inline help  icon is misaligned and it doesn't work when clicking on it.
`f:optionalProperty` doesn't support the help attribute, however the
underlying `f:optionalBlock` does. This adds a local copy of
optionalProperty with the help attribute which fixes the layout.
I filed in parallel https://github.com/jenkinsci/jenkins/pull/6615 to fix this at core level and allow removing the local tag copy later.
> Fix optional property layout of inline help

- pom.xml
- src/main/java/org/jenkinsci/plugins/saml/SamlFormValidation.java
Recent versions of the Mailer plugin have switched from JavaMail to Jakarta Mail. This plugin consumes this library via Mailer, so it needs to be adapted accordingly. Notably, the update to plugin BOM 1500.ve4d05cd32975 pulls in a new required version of Mailer, which has the Jakarta Mail imports.
CC @kuisathaverat
> Adapt to Jakarta Mail migration

- pom.xml
This is a code cleanup change; there is no urgent need for a release. This change removes hard-coded version numbers where they are not needed because a version is already provided by the BOM. This should make it easier to maintain this plugin by causing the creation of fewer Dependabot PRs.
> Use versions from BOM where possible

- src/main/java/org/jenkinsci/plugins/saml/OpenSAMLWrapper.java
the new pac4j-saml 5.4.6, requires an Optional "Destination" field in the SAML response to be present unless disabled with a setting
https://github.com/pac4j/pac4j/pull/1871
```
WARNING o.j.p.saml.SamlSecurityRealm#doFinishLogin: Unable to validate the SAML Response: SAML configuration does not allow response Destination to be null
For more info check 'Maximum Authentication Lifetime' at https://github.com/jenkinsci/saml-plugin/blob/master/doc/CONFIGURE.md#configuring-plugin-settings
If you have issues check the troubleshoting guide at https://github.com/jenkinsci/saml-plugin/blob/master/doc/TROUBLESHOOTING.md
org.pac4j.saml.exceptions.SAMLEndpointMismatchException: SAML configuration does not allow response Destination to be null
at …
```
> feat: olerate missing SAML response Destination attribute

- pom.xml
See [JENKINS-69898](https://issues.jenkins-ci.org/browse/JENKINS-69898).
I have added the Jackson API plugin dependency and exclude the Jackson library from the pac4j
> [JENKINS-69898] saml plugin affected by CVE -2022-42003;42004

- src/main/java/org/jenkinsci/plugins/saml/IdpMetadataConfiguration.java
Resolving XML external entity in user-controlled data
https://github.com/jenkinsci/saml-plugin/security/code-scanning/50
In the case the IdP metadata is configured to be downloaded from a trusted URL, the plugin resolves the external entities, to improve the security this PR disabled the external entities resolution.
> fix: disable external entities resolution

- src/main/java/org/jenkinsci/plugins/saml/IdpMetadataConfiguration.java
fix: change to use XMLUtils to process IdP Metadata
even though the method is already safe, looks better to use the Jenkins XMLUtils class that make s exactly the same 
related to https://github.com/jenkinsci/saml-plugin/pull/276
> fix: change to use XMLUtils to process IdP Metadata

- src/main/java/org/jenkinsci/plugins/saml/SamlAdvancedConfiguration.java
See [JENKINS-69930](https://issues.jenkins-ci.org/browse/JENKINS-69930).
> [JENKINS-69930] NullPointerException from getUseDiskCache in SAML plugin

- pom.xml
- src/main/java/org/jenkinsci/plugins/saml/SamlFormValidation.java
> Refresh plugin

- pom.xml
Removes `bcprov-jdk18on-1.71.jar` and `commons-lang3-3.11.jar` from the `WEB-INF/lib` directory of the HPI file in favor of the corresponding library plugins. This is the preferred mechanism for dynamic linking in the Jenkins plugin ecosystem. CC @kuisathaverat
> Stop bundling unnecessary libraries

- pom.xml
- src/test/java/org/jenkinsci/plugins/saml/LiveTest.java
Changes in the test framework cause the need for the baseline to be updated to 2.387 to pick up test JARs with the updated HtmlUnit imports.
Closes #348
> Upgrade HtmlUnit to 3.x

- Jenkinsfile
Java 21 released Sep 19, 2023. We'd like to announce full support for Java 21 in early October and would like the most used plugins to be compiling and testing with Java 21.
The acceptance test harness and plugin bill of materials tests are already passing with Java 21. This is a further step to improve plugin readiness for use with Java 21 and for development with Java 21.
Java 11 will be unsupported by Eclipse Temurin and some other Java providers in October 2024. We'll need to move past Java 11 by that time. It does not change the supported Java version or the byte code that is being generated.
This intentionally does not include Java 11 in the test configuration because Java 11 byte code is being generated by the Java 17 and Java 21 compilation and because Java 11 is being tested at …
> chore: Test with Java 21

- pom.xml
- src/test/java/org/jenkinsci/plugins/saml/OpenSamlWrapperTest.java
See [JENKINS-73316](https://issues.jenkins.io/browse/JENKINS-73316). Allow this plugin's test suite to be exercised regularly in Plugin Compatibility Tester (PCT) in https://github.com/jenkinsci/bom by requiring Java 17 or newer and Jenkins 2.475 (released today) or newer.
This PR goes against the usual advice from https://www.jenkins.io/doc/developer/plugin-development/choosing-jenkins-baseline/ by requiring a weekly release. The advantage is that this will allow plugin compatibility testing (PCT). The disadvantage is that new features and bug fixes can't be released to LTS users for another few months.
The choice is up to the maintainer as to whether or not to accept this PR. If this PR is rejected, we will stop testing this plugin in PCT.
> [JENKINS-73316] Require Java 17 and 2.475; adapt test suite to EE 9

- src/main/java/org/jenkinsci/plugins/saml/IdpMetadataConfiguration.java
- src/main/java/org/jenkinsci/plugins/saml/SamlFileResourceCache.java
- src/main/java/org/jenkinsci/plugins/saml/SamlFileResourceDisk.java
(I can file a Jira ticket if needed)
I recently investigated an issue reported by a user where Jenkins was working totally normally, but when they tried to change their security realm to SAML, they were unable to save the change. The issue seemed to be that they had JENKINS_HOME hard linked to an NFS mount point like `/my-mount`, and this broke the logic in the Apache Common IO utility methods that check for the existence of the file and create parent directories if needed. Here is the relevant part of the stack trace:
```
java.nio.file.AccessDeniedException: /my-mount
at java.base/sun.nio.fs.UnixException.translateToIOException(UnixException.java:90)
at java.base/sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:111)
at …
```
> Avoid Apache Commons IO utility methods when writing config files to `JENKINS_HOME` to fix `AccessDeniedException` in some cases

- Jenkinsfile
- pom.xml
- src/main/java/org/jenkinsci/plugins/saml/OpenSAMLWrapper.java
- src/main/java/org/jenkinsci/plugins/saml/SamlCrumbExclusion.java
- src/main/java/org/jenkinsci/plugins/saml/SamlProfileWrapper.java
- src/main/java/org/jenkinsci/plugins/saml/SamlRedirectActionWrapper.java
- src/main/java/org/jenkinsci/plugins/saml/SamlSPMetadataWrapper.java
- src/main/java/org/jenkinsci/plugins/saml/SamlSecurityRealm.java
- src/main/java/org/jenkinsci/plugins/saml/SamlValidateIdPMetadata.java
- src/main/java/org/jenkinsci/plugins/saml/user/LoginDetailsProperty.java
- src/main/java/org/jenkinsci/plugins/saml/user/SamlCustomProperty.java
- src/test/java/org/jenkinsci/plugins/saml/FakeRequest.java
- src/test/java/org/jenkinsci/plugins/saml/SamlCrumbExclusionTest.java
https://www.pac4j.org/blog/what_s_new_in_pac4j_v6.html
> Upgrade to pac4j 6.x, require Java 17 or newer, and migrate to EE 9

- pom.xml
Signed-off-by: Olivier Lamy <olamy@apache.org>
See [JENKINS-XXXXX](https://issues.jenkins-ci.org/browse/JENKINS-XXXXX).
> Remove not anymore needed exclusions which breaks PCT test from 2.489, test with mvn clean install -Djenkins.version=2.489
